sudo: false

language: php

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    php: 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - if [[ $(phpenv version-name) == '7.0' ]]; then composer require satooshi/php-coveralls:dev-master -n ; fi
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - if [[ $(phpenv version-name) == '7.0' ]]; then phpunit --coverage-clover build/logs/clover.xml ; fi
  - if [[ $(phpenv version-name) != '7.0' ]]; then phpunit ; fi

after_success:
  - if [[ $(phpenv version-name) == '7.0' ]]; then php vendor/bin/coveralls -v ; fi
